# /stacks/core.yml
services:
  socket-proxy: # Renamed from docker-socket-proxy for brevity, you can keep the old name
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z # Mount the actual Docker socket
    environment:
      # Configuration: Only allow specific API calls needed by Watchtower
      # These are examples; you might need to adjust based on Watchtower's exact needs.
      # Start with a minimal set and add if Watchtower logs errors.
      - LOG_LEVEL=info
      # Watchtower needs to list containers, inspect them, get versions, and sometimes events.
      # It might also need to get container logs if you use that feature for notifications.
      # Deny all by default, then allow specific GET requests:
      - POST=0 # Deny all POST requests (like creating containers, exec, etc.)
      - PUT=0
      - DELETE=0
      # Allow specific GET requests Watchtower likely needs:
      - CONTAINERS=1 # Allow /containers/* (inspect, list, logs)
      - SERVICES=0 # Watchtower usually doesn't manage services directly
      - TASKS=0 # Watchtower usually doesn't manage tasks directly
      - NODES=0 # Watchtower usually doesn't manage nodes directly
      - NETWORKS=0 # Watchtower usually doesn't manage networks directly
      - VOLUMES=0 # Watchtower usually doesn't manage volumes directly
      - IMAGES=1 # Allow /images/* (needed to check image updates)
      - INFO=1 # Allow /info
      - VERSION=1 # Allow /version
      - EVENTS=1 # Allow /events (for real-time updates)
      - PING=1 # Allow /_ping
    # Expose the proxy on a local port. Watchtower will connect to this.
    # Do NOT expose this port to the wider network.
    ports:
      - "127.0.0.1:2375:2375" # Listen only on localhost

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    depends_on: # Ensure socket-proxy starts before Watchtower
      - socket-proxy
    env_file:
      - ../.env
    environment:
      - WATCHTOWER_CLEANUP=true
      # Tell Watchtower to use the socket-proxy
      - DOCKER_HOST=tcp://socket-proxy:2375 # Use the service name 'socket-proxy' and its internal port
    # NO direct Docker socket mount here anymore!
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock:z # REMOVE THIS LINE
    labels:
      - com.centurylinklabs.watchtower.enable=true
